const tradingPair = {
  allowTrailingStop: true,
  allowedSelfTradePreventionModes: [
    'EXPIRE_TAKER',
    'EXPIRE_MAKER',
    'EXPIRE_BOTH',
  ],
  baseAsset: 'ETH',
  baseAssetPrecision: 8,
  baseCommissionPrecision: 8,
  cancelReplaceAllowed: true,
  defaultSelfTradePreventionMode: 'EXPIRE_MAKER',
  filters: [
    {
      filterType: 'PRICE_FILTER',
      minPrice: '0.00001000',
      maxPrice: '922327.00000000',
      tickSize: '0.00001000',
    },
    {
      filterType: 'LOT_SIZE',
      minQty: '0.00010000',
      maxQty: '100000.00000000',
      stepSize: '0.00010000',
    },
    { filterType: 'ICEBERG_PARTS', limit: 10 },
    {
      filterType: 'MARKET_LOT_SIZE',
      minQty: '0.00000000',
      maxQty: '2863.05405000',
      stepSize: '0.00000000',
    },
    {
      filterType: 'TRAILING_DELTA',
      minTrailingAboveDelta: 10,
      maxTrailingAboveDelta: 2000,
      minTrailingBelowDelta: 10,
      maxTrailingBelowDelta: 2000,
    },
    {
      filterType: 'PERCENT_PRICE_BY_SIDE',
      bidMultiplierUp: '5',
      bidMultiplierDown: '0.2',
      askMultiplierUp: '5',
      askMultiplierDown: '0.2',
    },
    {
      filterType: 'NOTIONAL',
      minNotional: '0.00010000',
      applyMinToMarket: true,
      maxNotional: '9000000.00000000',
      applyMaxToMarket: false,
    },
    { filterType: 'MAX_NUM_ORDERS', maxNumOrders: 200 },
    { filterType: 'MAX_NUM_ALGO_ORDERS', maxNumAlgoOrders: 5 },
  ],
  icebergAllowed: true,
  isMarginTradingAllowed: true,
  isSpotTradingAllowed: true,
  ocoAllowed: true,
  orderTypes: [
    'LIMIT',
    'LIMIT_MAKER',
    'MARKET',
    'STOP_LOSS_LIMIT',
    'TAKE_PROFIT_LIMIT',
  ],
  otoAllowed: false,
  permissionSets: [Array(23)], // assuming there's more detail in the array not fully shown here
  permissions: [],
  quoteAsset: 'BTC',
  quoteAssetPrecision: 8,
  quoteCommissionPrecision: 8,
  quoteOrderQtyMarketAllowed: true,
  quotePrecision: 8,
  status: 'TRADING',
  symbol: 'ETHBTC',
}
